**What is NLP?**
Natural Language Processing (NLP) is the field of Artificial Intelligence conserned with the processing and understanding of human language. Since its incetion during the 1950s, machine understanding of language has played a pivotal role in translation, topic modelin, document indexing, information retrieval, and extraction.

Application of NLP

*   Text Classification
*   Spam Filters
*   Voice Text Messaging
*   Sentimen Analysis
*   Spell or Grammer Check
*   Chat Bot
*   Search Suggestion
*   Search Autocorrect
*   Automatic Review Analysis System
*   Machine Translation
*   And so much more...

## Data Cleaning Options
   

*   Case Normalization
*   Removing Stop Words
*   Removing Punctuations or Special Symbols
*   Lemmatization or Stemming
*   Parts of Speech Tagging
*   Entity Detection
*   Bag of Words
*   TF-IDF https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfTransformer.html

1.   !pip install scikit-learn
1.   !pip install -U spacy
1.   !pip install -m spacy download en
1.   !python -m spacy download en_core_web_en

# PART-1 : Rule Baset Text Phrase Extraction

**Token Özellikleri (Attributes):**

Sözlüklerin içinde, token'ların özelliklerini belirtmek için anahtar-değer çiftleri kullanılır. İşte en sık kullanılan özellikler:

- `TEXT`: Token'ın tam metni (büyük/küçük harf duyarlı).

- `LOWER`: Token'ın küçük harfe çevrilmiş metni (büyük/küçük harf duyarsız arama için kullanışlı).

- `LEMMA`: Token'ın lemma'sı (kök hali).

- `POS`: Token'ın part-of-speech (POS) etiketi (örneğin, "NOUN", "VERB", "ADJ").

- `TAG`: Token'ın detaylı part-of-speech etiketi.

- `DEP`: Token'ın dependency parsing etiketi (cümlenin yapısındaki rolü).

- `SHAPE`: Token'ın şekli (örneğin, "Xxxx" büyük harfle başlayan bir kelime için, "dd" iki basamaklı bir sayı için).

- `IS_ALPHA`: Token'ın alfabetik karakterlerden oluşup oluşmadığı (True/False).

- `IS_DIGIT`: Token'ın rakamlardan oluşup oluşmadığı (True/False).

- `IS_PUNCT`: Token'ın noktalama işareti olup olmadığı (True/False).

- `IS_SPACE`: Token'ın boşluk olup olmadığı (True/False).

- `IS_STOP`: Token'ın stop word (sık kullanılan ve anlam taşımayan kelime) olup olmadığı (True/False).

- `LIKE_NUM`: Token'ın sayı gibi olup olmadığı (True/False).

- `LIKE_URL`: Token'ın URL gibi olup olmadığı (True/False).

- `LIKE_EMAIL`: Token'ın e-posta adresi gibi olup olmadığı (True/False).

**Operatörler (Operators):**

Her bir token özelliği için, eşleşme davranışını kontrol etmek için operatörler kullanılabilir.

- `"OP": "!"`: Token'ın olmaması gerektiğini belirtir (negation).

- `"OP": "?"`: Token'ın isteğe bağlı (optional) olduğunu belirtir (0 veya 1 kez).

- `"OP": "*"`: Token'ın 0 veya daha fazla kez tekrarlanabileceğini belirtir.

- `"OP": "+"`: Token'ın 1 veya daha fazla kez tekrarlanabileceğini belirtir.

Liste İçinde Birden Fazla Özellik:

Bir token için birden fazla özellik belirtebilirsiniz. Bu durumda, tüm özelliklerin eşleşmesi gerekir.

- pattern = `[{"LOWER": "apple", "IS_ALPHA": True, "IS_STOP": False}]`

**IN Operatörü:**

Bir özelliğin belirli bir değerler listesinden herhangi birine eşit olup olmadığını kontrol etmek için IN operatörünü kullanabilirsiniz.

`pattern = [{"POS": {"IN": ["NOUN", "PROPN"]}}]`

In [ ]:
#!pip install -U spacy
#!pip install -U spacy-lookups-data
#!python -m spacy download en_core_web_sm

In [ ]:
import spacy
from spacy.matcher import Matcher
from spacy.tokens import Span
from spacy import displacy

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
doc = nlp("Hello World!")
doc

Hello World!

In [ ]:
for token in doc:
  print(token)

Hello
World
!

In [ ]:
pattern = [{"LOWER":"hello", "OP":"?"},
           {"IS_PUNCT":True, "OP":"?"},
           {"LOWER":"world"}]

In [ ]:
matcher = Matcher(nlp.vocab)
matcher.add('HelloWorld', [pattern])

In [ ]:
matches = matcher(doc)
matches

[(15578876784678163569, 0, 2), (15578876784678163569, 1, 2)]

In [ ]:
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]
    span = doc[start:end]
    print(match_id, string_id, start, end, span.text)

15578876784678163569 HelloWorld 0 2 Hello World
15578876784678163569 HelloWorld 1 2 World

In [ ]:
doc = nlp('Hello, World!')

In [ ]:
matches = matcher(doc)
matches

[(15578876784678163569, 0, 3),
 (15578876784678163569, 1, 3),
 (15578876784678163569, 2, 3)]

In [ ]:
for token in doc:
  print(token)

Hello
,
World
!

In [ ]:
for match_id, start, end in matches:
    string_id = nlp.vocab.strings[match_id]
    span = doc[start:end]
    print(match_id, string_id, start, end, span.text)

15578876784678163569 HelloWorld 0 3 Hello, World
15578876784678163569 HelloWorld 1 3 , World
15578876784678163569 HelloWorld 2 3 World

* https://demos.explosion.ai/matcher
* https://demos.explosion.ai/displacy?text=hello%20world!&model=en_core_web_sm&cpu=0&cph=0

In [ ]:
text = "my phone number is 1234. Ohh its wrong! Correct one is 1234567890. Call me!"

###Regular Expression

In [ ]:
import re

In [ ]:
re.search(r'\d{4,10}', text)

In [ ]:
re.findall(r'\d{4,10}', text)

['1234', '1234567890']

In [ ]:
re.findall(r'\w{4}', text)

['phon', 'numb', '1234', 'wron', 'Corr', '1234', '5678', 'Call']

In [ ]:
re.findall(r'\w{4,}', text)

['phone', 'number', '1234', 'wrong', 'Correct', '1234567890', 'Call']

Wildcard Text

In [ ]:
re.findall(r'p...', text)

['phon']

In [ ]:
re.findall(r'c...', text)

['ct o']

In [ ]:
text = "this is cat but not that. i want hat and cat both"

In [ ]:
re.findall(r'.a.', text)

['cat', 'hat', 'wan', 'hat', ' an', 'cat']

In [ ]:
text = "hi thanks for reading <3"

In [ ]:
re.findall(r'\d$', text)

['3']

In [ ]:
text = "3 hi thanks for reading <3"

In [ ]:
re.findall(r'^\d', text)

['3']

### Exclusion

In [ ]:
text

'3 hi thanks for reading <3'

In [ ]:
re.findall(r'[^\d]+', text)

[' hi thanks for reading <']

In [ ]:
re.findall(r'[^\D]+', text)

['3', '3']

In [ ]:
re.findall(r'[^\w]+', text)

[' ', ' ', ' ', ' ', ' <']

In [ ]:
re.findall(r'[^\W]+', text)

['3', 'hi', 'thanks', 'for', 'reading', '3']

In [ ]:
text = "you can get free-classes on great account of kgp-talkie. Thank you Laxmi"

In [ ]:
re.findall(r'[\w]+-[\w]+', text)

['free-classes', 'kgp-talkie']

## Regular Expression in SpaCy
* Match Differen Spelling of Token Texts `pattern = [{"TEXT"}: {"REGEX":"deff?in[ia]tely"}}]`
* Match Tokens fith Fine-Grained POS Tags starting with 'V' `pattern = [{"TAG"}: {"REGEX":"^V"}}]`

In [ ]:
text = "Google announced a new Pixel at Google I/O . Google I/O is a great place to get all updates from Google"

In [ ]:
pattern = [{"TEXT": "Google"},
           {"TEXT": "I"},
           {"TEXT": "/"},
           {"TEXT": "O"}]

In [ ]:
def callback_method(matcher, doc, i, matches):
  match_id, start, end = matches[i]
  entity = doc[start:end]
  print(entity.text)

In [ ]:
matcher = Matcher(nlp.vocab)
matcher.add('GoogleIO', [pattern], on_match=callback_method)

In [ ]:
doc = nlp(text)

In [ ]:
matches = matcher(doc)

Google I/O
Google I/O

### Find Word Google

In [ ]:
pattern = [{"TEXT": "Google"},
           {"TEXT": "I", "OP": "?"},
           {"TEXT": "/", "OP": "?"},
           {"TEXT": "O", "OP": "?"}]

In [ ]:
def callback_method(matcher, doc, i, matches):
  match_id, start, end = matches[i]
  entity = doc[start:end]
  print(entity.text)

In [ ]:
matcher = Matcher(nlp.vocab)
matcher.add('GoogleIO', [pattern], on_match=callback_method)

In [ ]:
doc = nlp(text)

In [ ]:
matches = matcher(doc)

Google
Google
Google I
Google I/
Google I/O
Google
Google I
Google I/
Google I/O
Google

# PART-2 : Phone Number, Email, Emoji Extraction

> `[{"LOWER":"facebook"},{"LEMMA":"be"},{"POS":"ADV","OP":"*"},{"POS":"ADJ"}]`
- This translates to a token whose lowercase from matches "facebook" (like Facebook, facebook or FACEBOOK), followed by a token with the lemma "be" (for example; is, was, or`s), followed by an optional adverb, followed by an adjective.

In [ ]:
matcher = Matcher(nlp.vocab)

In [ ]:
matched_sents = []

In [ ]:
pattern = [{"LOWER":"facebook"},{"LEMMA":"be"},{"POS":"ADV","OP":"*"},{"POS":"ADJ"}]

In [ ]:
def callback_method_fb(matcher, doc, i, matches):
  matched_id, start, end = matches[i]
  span = doc[start:end]
  sent = span.sent

  match_ents = [{
      "start": span.start_char - sent.start_char,
      "end": span.end_char - sent.start_char,
      "label": "MATCH"
  }]

  matched_sents.append({"text": sent.text, "ents": match_ents})

In [ ]:
matcher.add("fb", [pattern], on_match=callback_method_fb)

In [ ]:
doc = nlp("I'd say that Facebook is evil. - Facebook is pretty cool, right?")

In [ ]:
matches = matcher(doc)
matches

[(8017838677478259815, 4, 7), (8017838677478259815, 9, 13)]

In [ ]:
matched_sents

[{'text': "I'd say that Facebook is evil.",
  'ents': [{'start': 13, 'end': 29, 'label': 'MATCH'}]},
 {'text': '- Facebook is pretty cool, right?',
  'ents': [{'start': 2, 'end': 25, 'label': 'MATCH'}]}]

In [ ]:
displacy.render(matched_sents, style="ent", manual=True)

## Phone Number Extraction
- Phone Numbers can have many different formats and matching them is often tricky. During `Tokenization`, spaCy will leave sequences of numbers intact and only split on whitespace and punctuation. This means that your match pattern will have to look out for number sequences of a certain length, surrounded by specific punctuation - depending on the national conventions.

- You want to match like this : `(123) 4567 8901 or (123) 4567-8901`
- [{"ORTH":"("}, {"SHAPE":"ddd"}, {"ORTH":")"}, {"SHAPE":"dddd"}, {"ORTH":"-", "OP":"?"}, {"SHAPE":"dddd"}]

In [ ]:
pattern = [{"ORTH":"("}, {"SHAPE":"ddd"}, {"ORTH":")"}, {"SHAPE":"dddd"}, {"ORTH":"-", "OP":"?"}, {"SHAPE":"dddd"}]

In [ ]:
matcher = Matcher(nlp.vocab)
matcher.add("PhoneNumber", [pattern])

In [ ]:
doc = nlp("Call me at (123) 4560-7890")

In [ ]:
print([t.text for t in doc])

['Call', 'me', 'at', '(', '123', ')', '4560', '-', '7890']

In [ ]:
matches = matcher(doc)
matches

[(7978097794922043545, 3, 9)]

In [ ]:
for match_id, start, end in matches:
  span = doc[start:end]
  print(span.text)

(123) 4560-7890

## E-Mail Address Matching

In [ ]:
pattern = [{"TEXT": {"REGEX": "[a-zA-Z0-9-_.]+@[a-zA-Z0-9-_.]+"}}]

In [ ]:
matcher = Matcher(nlp.vocab)
matcher.add("EMail", [pattern])

In [ ]:
text = "Email me at email2me@colemerg.com and talk.me@rido.com"

In [ ]:
doc = nlp(text)

In [ ]:
matches = matcher(doc)
matches

[(10208870021556473826, 3, 4), (10208870021556473826, 5, 6)]

In [ ]:
for match_id, start, end in matches:
  span = doc[start:end]
  print(span.text)

email2me@colemerg.com
talk.me@rido.com

## Hashtags and Emoji on Social Media
- Social media posts, especially tweets, can be difficult to work with. They're very short and often contain various emoji and hashtags. By only looking at the plain text, you'll lose a lot of valuable semantic information.
- Let's say you've extracted a large sample of social media posts and specific topic, for example posts mentioning a brand name or product. As the fist step of your data exploration, you want to filter out posts containing certain emoji and use them to assign a general sentiment score, based on wheter the expressed emotion is positive or negative, e.g. 😊 or 😢. You also want to find, marge and label hastags like #MondayMotivation, to be able to ignore analyze them later.
- By default, spaCy's tokenizer will split emoji into seperate tokens. This means that you can create a pattern for one or more emoji tokens. Valid hashtags usually consist of a #, plus a sequence of ASCII characters with no whitespace, making them easy to match as well.

In [ ]:
pos_emoji = ["😊", "😃", "😄", "😁", "😆", "😅"] #positive_emoji
neg_emoji = ["😞", "😔", "😟", "😕", "🙁", "☹️"] #negative_emoji

In [ ]:
pos_emoji, neg_emoji

(['😊', '😃', '😄', '😁', '😆', '😅'], ['😞', '😔', '😟', '😕', '🙁', '☹️'])

In [ ]:
# add patterns to match one or more emoji tokens
pos_patterns = [[{"ORTH": emoji}] for emoji in pos_emoji]
neg_patterns = [[{"ORTH": emoji}] for emoji in neg_emoji]

In [ ]:
pos_patterns

[[{'ORTH': '😊'}],
 [{'ORTH': '😃'}],
 [{'ORTH': '😄'}],
 [{'ORTH': '😁'}],
 [{'ORTH': '😆'}],
 [{'ORTH': '😅'}]]

In [ ]:
 neg_patterns

[[{'ORTH': '😞'}],
 [{'ORTH': '😔'}],
 [{'ORTH': '😟'}],
 [{'ORTH': '😕'}],
 [{'ORTH': '🙁'}],
 [{'ORTH': '☹️'}]]

In [ ]:
def label_sentiment(matcher, doc, i, matches):
  match_id, start, end = matches[i]
  if doc.vocab.strings[match_id] == "HAPPY":
    doc.sentiment += 0.1
  elif doc.vocab.strings[match_id] =='SAD':
    doc.sentiment -= 0.1

In [ ]:
matcher = Matcher(nlp.vocab)

In [ ]:
matcher.add("HAPPY", pos_patterns, on_match=label_sentiment)
matcher.add("SAD", neg_patterns, on_match=label_sentiment)

In [ ]:
matcher.add("HASHTAG", [[{"ORTH":"#"}, {"IS_ASCII":True}]])

In [ ]:
doc = nlp("Hello world 😊 #MondayMotivation")

In [ ]:
matches = matcher(doc)

In [ ]:
for match_id, start, end in matches:
  string_id = doc.vocab.strings[match_id] # look up string ID
  span = doc[start:end]
  print(string_id, span.text)

HAPPY 😊
HASHTAG #MondayMotivation

## Efficient Phrase Matching
- If you need to match large technology list, you dan also use the PhraseMatcher and create Doc objects instead of token patterns, which is much more efficient overall. The Doc patterns can contain single or multiple tokens.

In [ ]:
from spacy.matcher import PhraseMatcher

In [ ]:
matcher = PhraseMatcher(nlp.vocab)

In [ ]:
terms = ["BARACK OBAMA", "ANGELA MERKEL", "WASHINGTON D.C."]

In [ ]:
pattern = [nlp.make_doc(text) for text in terms]
pattern

[BARACK OBAMA, ANGELA MERKEL, WASHINGTON D.C.]

In [ ]:
matcher.add("term", pattern)

In [ ]:
doc = nlp("German Chancellor ANGELA MERKEL and US President BARACK OBAMA converse in the Oval Office inside the White House in WASHINGTON D.C.")
doc

German Chancellor ANGELA MERKEL and US President BARACK OBAMA converse in the Oval Office inside the White House in WASHINGTON D.C.

In [ ]:
matches = matcher(doc)

In [ ]:
for match_id, start, end in matches:
  span = doc[start:end]
  print(span.text)

ANGELA MERKEL
BARACK OBAMA
WASHINGTON D.C.

In [ ]:
matches

[(4519742297340331040, 2, 4),
 (4519742297340331040, 7, 9),
 (4519742297340331040, 19, 21)]

## Custome Rule Based Entity Recognition
- The EntityRuler is an exciting new component that lets you add named entities based on pattern dictionaries, and makes it easy to combine rule-based and statistical named entity recognition for even more powerful models.

#### Entity Patterns
- Entity patterns are dictionaries with two keys: "label", specifying the label to assign to the entity if the pattern is matched, and "patter", the match pattern. The entity ruler accepts two types of patterns:


1.   Phrase Pattern `{"label":"ORG", "pattern":"Apple"}`
2.   Token Pattern `{"label":"GPE", "pattern":[{"LOWER":"san"},{{"LOWER":"francisco"}]}`

#### Using the Entity Ruler
- The EntityRuler is a pipeline component that's typically added via nlp_add.pipe. When the nlp object is called on a text, it will find matches in the doc and add them as entities to the doc.ents, using the specified pattern label as the entity label.

* https://spacy.io/api/annotation#named-entities

In [ ]:
from spacy.pipeline import EntityRuler

In [ ]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
ruler = nlp.add_pipe("entity_ruler", name="entity_ruler", before="ner")

In [ ]:
patterns = [{"label":"ORG", "pattern":"Apple"},
          {"label":"GPE", "pattern":[{"LOWER":"san"}, {"LOWER":"francisco"}]}]
patterns

[{'label': 'ORG', 'pattern': 'Apple'},
 {'label': 'GPE', 'pattern': [{'LOWER': 'san'}, {'LOWER': 'francisco'}]}]

In [ ]:
ruler.add_patterns(patterns)

In [ ]:
doc = nlp("Apple is opening a new store in San Francisco")

In [ ]:
print([(ent.text, ent.label_) for ent in doc.ents])

[('Apple', 'ORG'), ('San Francisco', 'GPE')]

# Part-3 Combining NLP Models and Custom Rules
You can combine statistical and rule-based components in variaty of ways. Rule-based components can be used to improve the accuracy of statistical models, by presetting tags, entities or sentence boundaries for specific tokens. The statistical models will usually respect these preset annotations, which sometimes improves the accuracy of other decisions. You can also use rule-based components after a statistical model to correct common errors. Finally, rule-based components can reference the attributes set by statistical models, in order to implement more abstract logic.

## Expanding Named Entities
For example, the corpus spaCy's English models were trained on defines a PERSON entity as just the person name, without titles like "Mr" or "Dr". This makes sense, because it makes it easier to resolve the entity type back to a knowledge base. But what if your application needs the full names, including the titles?

- Mr. Ridvan Yigit

In [ ]:
import spacy
from spacy.tokens import Span
from spacy import displacy
from spacy.language import Language

In [ ]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
doc = nlp("Dr. Alex Smith chaired first board meeting at Google")
doc

Dr. Alex Smith chaired first board meeting at Google

In [ ]:
print([(ent.text, ent.label_) for ent in doc.ents])

[('Alex Smith', 'PERSON'), ('first', 'ORDINAL'), ('Google', 'ORG')]

In [ ]:
@Language.component("add_title")
def add_title(doc):
  new_ents = []
  for ent in doc.ents:
    if ent.label_ == "PERSON" and ent.start != 0:
      prev_token = doc[ent.start - 1]
      if prev_token.text in ("Dr.", "Mr.", "Mrs."):
        new_ent = Span(doc, ent.start - 1, ent.end, label=ent.label_)
        new_ents.append(new_ent)
      else:
        new_ents.append(ent)
  doc.ents = new_ents
  return doc

In [ ]:
nlp = spacy.load("en_core_web_sm")
nlp.add_pipe("add_title", after="ner")

In [ ]:
doc = nlp("Dr. Alex Smith chaired first board meeting at Google")
print([(ent.text, ent.label_) for ent in doc.ents])

[('Dr. Alex Smith', 'PERSON')]

## Use of POS and Dep Parsing

In [ ]:
import spacy
from spacy.language import Language

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
doc = nlp("Alex Smith was working at Google")
doc

Alex Smith was working at Google

In [ ]:
displacy.render(doc, style="dep", options={"compact":True, "distance":200})

In [ ]:
@Language.component("get_person_orgs")
def get_person_orgs(doc):
  person_entities = [ent for ent in doc.ents if ent.label_=="PERSON"]
  for ent in person_entities:
    head = ent.root.head
    if head.lemma_ == "work":
      preps = [token for token in head.children if token.dep_ == "prep"]
      for prep in preps:
        orgs = [token for token in prep.children if token.ent_type_ == "ORG"]
        if orgs:
          print({"person": ent.text, "orgs": [org.text for org in orgs], "past": head.tag_ == "VBD"})
  return doc

In [ ]:
nlp.add_pipe("get_person_orgs")
doc = nlp("Alex Smith was working at Google")

{'person': 'Alex Smith', 'orgs': ['Google'], 'past': False}

In [ ]:
displacy.render(doc, style="dep", options={"compact":True, "distance":200})

Modify Model

In [ ]:
import spacy
from spacy.language import Language

In [ ]:
nlp = spacy.load('en_core_web_sm')

In [ ]:
@Language.component("get_person_orgs")
def get_person_orgs(doc):
  person_entities = [ent for ent in doc.ents if ent.label_=="PERSON"]
  for ent in person_entities:
    head = ent.root.head
    if head.lemma_ == "work":
      preps = [token for token in head.children if token.dep_ == "prep"]
      orgs = []
      for prep in preps:
        orgs.extend([token.text for token in prep.children if token.ent_type_ == "ORG"])

      aux = [token for token in head.children if token.dep_ == "aux"]
      past_aux = any(t.tag_ == "VBD" for t in aux)
      past = head.tag_ == "VBD" or (head.tag_ == "VBG" and past_aux)

      if orgs:
          print({"person": ent.text, "orgs": orgs, "past": past})
  return doc

In [ ]:
nlp.add_pipe("get_person_orgs")

In [ ]:
doc = nlp("Alex Smith was working at Google")

{'person': 'Alex Smith', 'orgs': ['Google'], 'past': True}

# PART-4 Sentiment Classification using SpaCy for IMDB and Amazon Review Dataset
*   Case Normalization
*   Removing Stop Words
*   Removing Punctuations or Special Symbols
*   Lemmatization or Stemming
*   Parts of Speech Tagging
*   Entity Detection
*   Bag of Words
*   TF-IDF

In [ ]:
import spacy
from spacy import displacy

In [ ]:
nlp = spacy.load("en_core_web_sm")

In [ ]:
text = "Apple, This is first sentence. and Google this is another one. here 3rd on is."

In [ ]:
doc = nlp(text)

In [ ]:
doc

Apple, This is first sentence. and Google this is another one. here 3rd on is.

In [ ]:
for token in doc:
  print(token)

Apple
,
This
is
first
sentence
.
and
Google
this
is
another
one
.
here
3rd
on
is
.

In [ ]:
sent = nlp.create_pipe("sentencizer")

In [ ]:
nlp.add_pipe("sentencizer", before="parser")

In [ ]:
doc = nlp(text)
for sent in doc.sents:
  print(sent)

Apple, This is first sentence.
and Google this is another one.
here 3rd on is.

STOPWORDS

In [ ]:
from spacy.lang.en.stop_words import STOP_WORDS

In [ ]:
stopwords = list(STOP_WORDS)
print(stopwords)

['hereafter', 'but', 'nobody', 'as', 'made', 'against', 'whither', 'fifteen', 'really', 'less', 'they', 'be', 'and', 'somehow', 'forty', 'thru', 'say', 'below', '‘d', 'former', 'four', 'into', 'empty', 'mine', 'about', 'nor', 'eight', 'herself', 'had', 'the', 'just', 'anywhere', 'been', 'bottom', 'beyond', 'when', 'whereby', 'do', 'can', 'front', 'down', 'if', 'both', 'this', 'out', 'seems', 'nothing', 'many', '‘m', 'none', 'either', "'re", 'it', 'me', 'ca', '’m', 'toward', 'first', 'upon', 'next', 'for', 'show', 'also', 'put', 'nowhere', 'moreover', 'among', 'various', 'these', 'your', 'must', 'herein', 'them', 'anyone', 'does', 'full', 'except', 'sometime', 'even', "'s", 'six', 'per', 'further', 'where', 'still', 'much', 'may', 'though', 'well', 'by', 'amongst', 'not', 'sometimes', 'same', 'five', 'how', '‘ve', 'such', 'or', '’d', 'another', 'during', 'before', 'their', '‘s', 'hundred', 'every', 'anything', 'was', 'here', 'thence', 'whenever', 'although', 'anyway', 'from', 'only', 'what', 'own', 'make', 'her', 'seem', 'often', 'ours', 'elsewhere', 'quite', 'will', 'of', 'others', 'yet', 'everything', 'on', 'serious', 'back', 'perhaps', 'several', 'whereafter', 'everyone', 'whether', 'we', 'since', 'ourselves', 'thereby', 'there', 'whence', 'up', 'last', 'because', 'him', 'you', 'above', 'each', 'some', 'am', 'no', 'two', 'please', 'all', 'neither', 'he', 'seemed', 'n‘t', 'yours', 'third', 'onto', 'amount', 'she', 'yourselves', 'twenty', 'becoming', 'towards', 'move', 'who', 'namely', 'enough', 'his', 'together', 'might', 'while', 'have', 'my', 'else', 'throughout', 'done', 'never', 'than', 'then', 'fifty', 'in', 'now', 'therein', 'indeed', 'always', "'ve", 'yourself', 'doing', 'ten', 'thus', 'via', 'an', 'that', 'seeming', 'become', 'wherein', "'m", '’ll', 'unless', 'off', 'alone', 'were', 'formerly', 'get', 'with', 'beside', 'would', 'thereupon', 'hereupon', 'latterly', 'myself', 'so', '’s', 'whole', 'across', 'side', '‘ll', 'three', 'within', 'has', 'most', 'due', 'between', 'take', 'see', 'hereby', 'along', '’ve', 'regarding', 'more', 'however', 'noone', 'whoever', 'is', 'therefore', 'otherwise', 'almost', 'did', 'one', 'cannot', 'behind', "'ll", 'something', 'name', 'beforehand', 'after', 'itself', 're', 'anyhow', 'latter', 'until', '‘re', 'mostly', 'which', 'nine', 'hers', 'its', 'became', 'over', 'twelve', "n't", 'few', 'hence', 'whereupon', 'any', 'us', 'whereas', 'being', 'those', "'d", 'someone', 'give', 'very', 'part', 'somewhere', 'i', 'using', 'should', 'other', 'n’t', 'through', 'already', 'themselves', 'thereafter', '’re', 'are', 'ever', 'could', 'besides', 'once', 'again', 'everywhere', 'sixty', 'meanwhile', 'go', 'whatever', 'under', 'whose', 'call', 'afterwards', 'eleven', 'why', 'himself', 'too', 'around', 'a', 'least', 'whom', 'keep', 'used', 'top', 'becomes', 'to', 'our', 'at', 'rather', 'nevertheless', 'without', 'wherever']

In [ ]:
len(stopwords)

326

In [ ]:
doc

Apple, This is first sentence. and Google this is another one. here 3rd on is.

In [ ]:
for token in doc:
  if token.is_stop==True:
    print(token)

This
is
first
and
this
is
another
one
here
on
is

## Lemmatization

In [ ]:
doc = nlp("run runs running runner")

In [ ]:
for lem in doc:
  print(lem.text, lem.lemma_)

run run
runs run
running run
runner runner

## POS (Part of Speech)

In [ ]:
doc = nlp("All is well at your end!")

In [ ]:
for token in doc:
  print(token.text, token.pos_)

All PRON
is AUX
well ADV
at ADP
your PRON
end NOUN
! PUNCT

Displacy , style="dep"

In [ ]:
displacy.render(doc, style="dep")

## Entity Detection

In [ ]:
doc = nlp("New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid on outbreak, becoming the latest national flash point over refusals to inoculate against dangeraus diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn's Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthod ox Jews, to receive incluations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.")
doc

New York City on Tuesday declared a public health emergency and ordered mandatory measles vaccinations amid on outbreak, becoming the latest national flash point over refusals to inoculate against dangeraus diseases. At least 285 people have contracted measles in the city since September, mostly in Brooklyn's Williamsburg neighborhood. The order covers four Zip codes there, Mayor Bill de Blasio (D) said Tuesday. The mandate orders all unvaccinated people in the area, including a concentration of Orthod ox Jews, to receive incluations, including for children as young as 6 months old. Anyone who resists could be fined up to $1,000.

Displacy , style="ent"

In [ ]:
displacy.render(doc, style="ent")

## Text Classification

In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfTransformer, TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
data_yelp = pd.read_csv("https://raw.githubusercontent.com/ridvanyigit/All-Datasets/refs/heads/main/sentiment%20labelled%20sentences/yelp_labelled.txt", sep="\t", header=None)
data_yelp.head()

                                                   0  1
0                           Wow... Loved this place.  1
1                                 Crust is not good.  0
2          Not tasty and the texture was just nasty.  0
3  Stopped by during the late May bank holiday of...  1
4  The selection on the menu was great and so wer...  1

In [ ]:
columns_name = ['Review', 'Sentiment']
data_yelp.columns = columns_name
data_yelp.head()

                                              Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [ ]:
data_yelp.shape

(1000, 2)

In [ ]:
data_amazon = pd.read_csv("https://raw.githubusercontent.com/ridvanyigit/All-Datasets/refs/heads/main/sentiment%20labelled%20sentences/amazon_cells_labelled.txt", sep="\t", header=None)
data_amazon.columns = columns_name
data_amazon.head()

                                              Review  Sentiment
0  So there is no way for me to plug it in here i...          0
1                        Good case, Excellent value.          1
2                             Great for the jawbone.          1
3  Tied to charger for conversations lasting more...          0
4                                  The mic is great.          1

In [ ]:
data_amazon.shape

(1000, 2)

In [ ]:
data_imdb = pd.read_csv("https://raw.githubusercontent.com/ridvanyigit/All-Datasets/refs/heads/main/sentiment%20labelled%20sentences/imdb_labelled.txt", sep="\t", header=None)
data_imdb.columns = columns_name
data_imdb.head()

                                              Review  Sentiment
0  A very, very, very slow-moving, aimless movie ...          0
1  Not sure who was more lost - the flat characte...          0
2  Attempting artiness with black & white and cle...          0
3       Very little music or anything to speak of.            0
4  The best scene in the movie was when Gerardo i...          1

In [ ]:
data_imdb.shape

(748, 2)

In [ ]:
data = pd.concat([data_yelp, data_amazon, data_imdb], ignore_index=True)
data.shape

(2748, 2)

In [ ]:
data.head()

                                              Review  Sentiment
0                           Wow... Loved this place.          1
1                                 Crust is not good.          0
2          Not tasty and the texture was just nasty.          0
3  Stopped by during the late May bank holiday of...          1
4  The selection on the menu was great and so wer...          1

In [ ]:
data['Sentiment'].value_counts()

Sentiment
1    1386
0    1362
Name: count, dtype: int64

In [ ]:
data.isnull().sum()

Review       0
Sentiment    0
dtype: int64

Tokenization

In [ ]:
import string

In [ ]:
punct = string.punctuation
punct

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [ ]:
def text_data_cleaning(sentence):
  doc = nlp(sentence)

  tokens = []
  for token in doc:
    if token.lemma_ != "-PRON-":
      temp = token.lemma_.lower().strip()
    else:
      temp = token.lower_
    tokens.append(temp)

  cleaned_tokens = []
  for token in tokens:
    if token not in stopwords and token not in punct:
      cleaned_tokens.append(token)
  return cleaned_tokens

In [ ]:
text_data_cleaning("       Hello all, It's a beautiful day outside there!")

['hello', 'beautiful', 'day', 'outside']

Vectorization Feature Engineering (TF-IDF)

In [ ]:
from sklearn.svm import LinearSVC

In [ ]:
tfidf = TfidfVectorizer(tokenizer=text_data_cleaning)
classifier = LinearSVC()

In [ ]:
X = data['Review']
y = data['Sentiment']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.shape, X_test.shape

((2198,), (550,))

In [ ]:
X_train

1670    its extremely slow and takes forever to do any...
2487    There are many continuity errors: one other us...
1124                                   Gets the job done.
2480                         This is an excellent film.
480     We asked for the bill to leave without eating ...
                              ...
1638    I used bitpim (a free program you can find on ...
1095                          Will order from them again!
1130    It is so small and you don't even realize that...
1294    The voice recognition thru the handset is exce...
860     This place is pretty good, nice little vibe in...
Name: Review, Length: 2198, dtype: object

In [ ]:
clf = Pipeline([('tfidf', tfidf), ('clf', classifier)])

In [ ]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.11/dist-packages/sklearn/feature_extraction/text.py:517: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

Pipeline(steps=[('tfidf',
                 TfidfVectorizer(tokenizer=<function text_data_cleaning at 0x7af65579d120>)),
                ('clf', LinearSVC())])

In [ ]:
y_pred = clf.predict(X_test)

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.77      0.81      0.79       285
           1       0.78      0.74      0.76       265

    accuracy                           0.78       550
   macro avg       0.78      0.78      0.78       550
weighted avg       0.78      0.78      0.78       550

In [ ]:
confusion_matrix(y_test, y_pred)

array([[230,  55],
       [ 68, 197]])

In [ ]:
clf.predict(["This movie was fantastic! I loved the storyline and the special effects."]) # Positive : 1

array([1])

In [ ]:
clf.predict(["The food was terrible. It was cold, bland, and overpriced."]) # Negative : 0

array([0])